# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 26047ceca419d9c0a8633d7c8aad90321a7e0127b87696fac673e1db2d6adcc18cc6ff6e5d1147c7f11e15c7895a38f6caa8ed9de12f5d5f2197940645f71f89

test:
  secret_key_base: 2d7e71a25dbe121220674a30981dc23cc71becd59f79e50227b164b01384e27bc892add33d9a33672e9bcd21a9f63ff1ac82cbda87c894bcd6d608507c6574fc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
